# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    # branches: [ dev ]

jobs:
  build:
    name: testing and building
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build api
      run: |
        docker build ./api -t viktors11/api
    - name: docker build myapp
      run: |
        docker build ./myapp -t viktors11/myapp
    - name: docker push
      run: |
        docker push viktors11/api
        docker push viktors11/myapp
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './myapp/package-lock.json'
    - run: cd myapp && npm ci
    - run: cd myapp && npm test
    - run: cd myapp && npm run build --if-present